theme: jekyll-theme-time-machine
title: [The title of your blog]
description: [A short description of your blog's purpose]
url: [Canonical URL for this blog]
author: the chef
paginate: [Number of posts in one paginated section (default: 3)]
owner: chef
year: 2020
