theme: jekyll-theme-hacker
title: [The title of your blog]
description: [A short description of your blog's purpose]
url: [Canonical URL for this blog]
author:
  name: [Your name]
  email: [Your email address]
  url: [URL of your website]

paginate: [Number of posts in one paginated section (default: 3)]
owner: [Your name]
year: [Current Year]
